# Generated by Django 5.1.7 on 2025-03-27 11:24

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi-yearly', 'Bi-Yearly'), ('yearly', 'Yearly')], max_length=20)),
                ('pricing', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='single_active_subscription')],
            },
        ),
    ]
