# Generated by Django 5.1.7 on 2025-03-29 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_content_ai_relevance_score'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('Viewed', 'Viewed'), ('Liked', 'Liked'), ('Skipped', 'Skipped'), ('Shared', 'Shared')], max_length=20)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-creation_timestamp'], name='core_userin_user_id_8ddd1a_idx'), models.Index(fields=['content', 'interaction_type'], name='core_userin_content_759dcb_idx')],
            },
        ),
    ]
