# Generated by Django 5.1.7 on 2025-03-30 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_content_ai_relevance_score'),
        ('core', '0002_userinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', '-id'], name='core_subscr_user_id_fa905a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['active', 'auto_renew', 'end_date'], name='core_subscr_active_f06788_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='core_userin_user_id_100a12_idx'),
        ),
    ]
