# Generated by Django 5.1.7 on 2025-03-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_category_alter_content_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_by',
            new_name='user',
        ),
    ]
