# Generated by Django 5.1.7 on 2025-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_category_description_alter_content_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
