# Generated by Django 5.1.7 on 2025-03-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ai_relevance_score',
            field=models.FloatField(default=0.0, help_text='Precomputed AI score (0.0-1.0)'),
        ),
    ]
