# Generated by Django 5.1.7 on 2025-03-31 06:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
